[package]
name = "bezotcorp_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.13"
euclid = "0.22.14"

vello = "0.9"

cosmic-text = "0.19"
parley = "0.10"

resvg = "0.47"
usvg = "0.47"

tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13.4", features = ["gzip", "brotli"] }

url = "2.5"
ron.workspace = true
serde = { workspace = true }
tracing = "0.1.44"
thiserror = "2.0.18"

rustls = "0.23.40"
