#[derive(Debug, Clone)]
pub(crate) enum RenderCommand {
    Clear {
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    Text {
        x: f32,
        y: f32,
        value: String,
        font_size: f32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    Rect {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    RoundedRect {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        radius: f32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    Line {
        x1: f32,
        y1: f32,
        x2: f32,
        y2: f32,
        thickness: f32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    Image {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        src: String,
    },
    Clip {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
    },
    RestoreClip,
}
